### ISSUE TITLE
NotaAlarma

### ISSUE THREAD

**Issue by ioliasa** [AlbertoAdame/EjerciciosPOOAvanzados#2]
En el constructor recibes la fechaAlarma pero no la usas para nada. Además no compruebas la exception de que la fecha de alarma no puede ser anterior a la fecha de creación. Ni en el método setFechaAlarma.
En el meodo isActivado, devuelve el booleano que tienes como atributo.

**Comment by AlbertoAdame** [comment]
No entiendo que tiene que hacer el método "esActivado" exactamento.

**Comment by AlbertoAdame** [comment]
Y el "setFechaAlarma" no entiendo porqué está privado en el UML.

**Comment by ioliasa** [comment]
En el método isActivado como lo tienes funciona bien, pero lo veo un poco absurdo. Lo que debe hacer es devolver true si la alarma está activada y false en caso contrario, tu tienes una variable que está a true si la alarma está activada y false en caso contrario, por lo que este método simplemente deberías devovler ese atributo y ya está. 
En cuanto al setFechaAlarma nos dicen que una vez que se crea la alarma no se puede modificar, aunque pueda ser un poco absurdo eso es lo que nos dicen, eso es lo que hacemos.

**Comment by ioliasa** [comment]
En el constructor debes usar el setFechaAlarma, y tienes que controlar que no sea nula
