### ISSUE TITLE
Bloc

### ISSUE THREAD

**Issue by ioliasa** [AlbertoAdame/EjerciciosPOOAvanzados#3]
En el constructor tienes que crear el array

En los métodos que sean sobre una nota, comprueba que existe esa nota.

OrdenaBloc no tiene sentido.

AñadirNota, comprueba que puedes añadir la nota, es decir, que no te sales del array

**Comment by AlbertoAdame** [comment]
Para comprobar si existe la nota, ¿puede crear una nueva clase "ExceptionBloc" aunque no salga en el UML, o lo paso a través de ExceptionNota?

**Comment by ioliasa** [comment]
Deberías crear un ExceptionBloc, aunque también es verdad que debería estar en el UML

**Comment by ioliasa** [comment]
OrdenaBloc te va a lanzar una Exception. BorrarNota no borra nada
