### ISSUE TITLE
Corrección de examen subida

### ISSUE THREAD

**Issue by AlbertoAdame** [AlbertoAdame/EjerciciosPOOAvanzados#7]

**Comment by ioliasa** [comment]
Tienes que asingarmela

**Comment by AlbertoAdame** [comment]
Tenía la versión buena en el portatil, todas las cosas que están con comentarios las hice en su momento, adicionalmente he colocado el "setTexto" en el constructor. He vuelto a poner "Tercer commit" sin querer. Los próximos proyectos los entregaré en el nuevo directorio.
