### ISSUE TITLE
Publicación

### ISSUE THREAD

**Issue by ioliasa** [AlbertoAdame/EjerciciosPOOAvanzados#8]
En el constructor de publicación usa el setTexto para asignar el texto y luego el constructor de la subclase mirará el setTexto de la subclase.
En valorar no escribas nada, lanza la exception adecuada
El compareTo no está muy bien pensado.
En las subclases valorar tienes que usar el del padre.

**Comment by AlbertoAdame** [comment]
El último apartado no estoy seguro si lo corregí, y si no lo hice, no entiendo que me pides.

**Comment by ioliasa** [comment]
Usa valorar del padre en los hijos
